#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
valid_name() { [[ "$1" =~ ^[A-Za-z0-9_-]{1,128}$ ]]; }

configure_transport() {
  ask ONSITE_AGENT_TRANSPORT 'Deployment mode: iot or fbi [iot]:'
  ONSITE_AGENT_TRANSPORT=${ONSITE_AGENT_TRANSPORT:-iot}
  case "$ONSITE_AGENT_TRANSPORT" in
    iot) ;;
    fbi)
      ask MAX_FBI_WATCH_DIR 'FBI folder [/srv/samba/fbi]:'
      MAX_FBI_WATCH_DIR=${MAX_FBI_WATCH_DIR:-/srv/samba/fbi}
      ask FBI_GROUP 'FBI folder group [fbi]:'
      FBI_GROUP=${FBI_GROUP:-fbi}
      ask MAX_FBI_LOCAL_DB_PATH 'Local database [/var/lib/spoke-onsite/max-fbi-agent.sqlite]:'
      MAX_FBI_LOCAL_DB_PATH=${MAX_FBI_LOCAL_DB_PATH:-/var/lib/spoke-onsite/max-fbi-agent.sqlite}
      [[ "$FBI_GROUP" =~ ^[a-zA-Z_][a-zA-Z0-9_-]{0,31}$ ]] || die 'Invalid Linux group name.'
      for value in "$MAX_FBI_WATCH_DIR" "$MAX_FBI_LOCAL_DB_PATH"; do
        [[ "$value" == /* && "$value" != *$'\n'* && "$value" != *$'\r'* ]] || die 'Use absolute paths without line breaks.'
      done
      [[ "$MAX_FBI_LOCAL_DB_PATH" != */ ]] || die 'The database path must name a file.'
      export MAX_FBI_WATCH_DIR MAX_FBI_LOCAL_DB_PATH
      write_env MAX_FBI_WATCH_DIR "$MAX_FBI_WATCH_DIR"
      write_env FBI_GROUP "$FBI_GROUP"
      write_env MAX_FBI_LOCAL_DB_PATH "$MAX_FBI_LOCAL_DB_PATH"
      say "Will add ggc_user to $FBI_GROUP and create the group/folder if missing."
      say 'Configure MAX to write FBI.csv and FBI.sem here; Samba/share setup is separate.'
      ;;
    *) die 'Choose iot or fbi.' ;;
  esac
  export ONSITE_AGENT_TRANSPORT
  write_env ONSITE_AGENT_TRANSPORT "$ONSITE_AGENT_TRANSPORT"
}

prepare_fbi_access() {
  getent group "$FBI_GROUP" >/dev/null || sudo groupadd "$FBI_GROUP"
  sudo usermod -aG "$FBI_GROUP" ggc_user
  if [[ ! -d "$MAX_FBI_WATCH_DIR" ]]; then
    sudo install -d -o root -g "$FBI_GROUP" -m 2770 -- "$MAX_FBI_WATCH_DIR"
  fi
  # Existing shares retain their ownership and permissions.
  sudo -u ggc_user test -r "$MAX_FBI_WATCH_DIR" &&
    sudo -u ggc_user test -w "$MAX_FBI_WATCH_DIR" &&
    sudo -u ggc_user test -x "$MAX_FBI_WATCH_DIR" ||
    die "ggc_user needs read/write/traverse access to $MAX_FBI_WATCH_DIR (including parent directories)."
  local probe db_dir
  probe=$(sudo -u ggc_user mktemp "$MAX_FBI_WATCH_DIR/.spoke-access.XXXXXX")
  sudo -u ggc_user rm -- "$probe"
  if [[ -e "$MAX_FBI_WATCH_DIR/FBI.csv" ]]; then
    sudo -u ggc_user test -r "$MAX_FBI_WATCH_DIR/FBI.csv" || die 'ggc_user cannot read the existing FBI.csv.'
  fi
  db_dir=$(dirname -- "$MAX_FBI_LOCAL_DB_PATH")
  if [[ ! -d "$db_dir" ]]; then
    sudo install -d -o ggc_user -g ggc_group -m 700 -- "$db_dir"
  fi
  sudo -u ggc_user test -w "$db_dir" && sudo -u ggc_user test -x "$db_dir" ||
    die "ggc_user needs write/traverse access to $db_dir for SQLite."
  if [[ -e "$MAX_FBI_LOCAL_DB_PATH" ]]; then
    sudo -u ggc_user test -r "$MAX_FBI_LOCAL_DB_PATH" &&
      sudo -u ggc_user test -w "$MAX_FBI_LOCAL_DB_PATH" || die 'ggc_user cannot read/write the existing database.'
  fi
  sudo systemctl restart greengrass
}

validate_hub_credentials() {
  node <<'JS'
const { createPrivateKey } = require('node:crypto');
try {
  const url = new URL(process.env.HUB_BASE_URL);
  if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash ||
      !url.pathname.endsWith('/api')) throw Error();
  if (!/^[A-Za-z0-9_-]+$/.test(process.env.ONSITE_AGENT_CLIENT_ID || '')) throw Error();
  const key = createPrivateKey({key: Buffer.from(process.env.ONSITE_AGENT_PRIVATE_KEY || '', 'base64'), format: 'der', type: 'pkcs8'});
  if (key.asymmetricKeyType !== 'ed25519') throw Error();
} catch {
  console.error('Use an HTTPS Hub URL ending in /api, a client ID and the single-line private key from Hub.');
  process.exit(1);
}
JS
}

deployment_json() {
  jq -n '{
    targetArn: env.THING_ARN,
    deploymentName: ("onsite-setup-" + env.THING_NAME),
    components: {"com.spokehub.OnsiteAgent": {
      componentVersion: env.COMPONENT_VERSION,
      configurationUpdate: {merge: ({
        HubBaseUrl: env.HUB_BASE_URL,
        OnsiteAgentClientId: env.ONSITE_AGENT_CLIENT_ID,
        OnsiteAgentPrivateKey: env.ONSITE_AGENT_PRIVATE_KEY,
        OnsiteAgentTransport: env.ONSITE_AGENT_TRANSPORT,
        OnsiteAgentVersion: env.COMPONENT_VERSION,
        OnsiteAgentIotTopicPrefix: "spoke/onsite-agents",
        accessControl: {"aws.greengrass.ipc.mqttproxy": {
          "com.spokehub.OnsiteAgent:mqttproxy:1": {
            policyDescription: "Receive onsite commands",
            operations: ["aws.greengrass#SubscribeToIoTCore"],
            resources: [("spoke/onsite-agents/" + env.ONSITE_AGENT_CLIENT_ID + "/commands")]
          }
        }}
      } + (if env.ONSITE_AGENT_TRANSPORT == "fbi" then {
        MaxFbiWatchDir: env.MAX_FBI_WATCH_DIR,
        MaxFbiLocalDbPath: env.MAX_FBI_LOCAL_DB_PATH,
        MaxFbiDeleteProcessedFiles: "false"
      } else {} end) | tojson)}
    }}
  }'
}

wait_for_deployment() {
  local status deadline=$((SECONDS + 900))
  while (( SECONDS < deadline )); do
    status=$(aws greengrassv2 list-effective-deployments --core-device-thing-name "$THING_NAME" \
      --output json | jq -r --arg id "$DEPLOYMENT_ID" \
      '[.effectiveDeployments[] | select(.deploymentId == $id)][0].coreDeviceExecutionStatus // "QUEUED"')
    case "$status" in
      SUCCEEDED) return 0 ;;
      FAILED|REJECTED|TIMED_OUT|CANCELED) die "Deployment $DEPLOYMENT_ID ended with $status. Check /greengrass/v2/logs/com.spokehub.OnsiteAgent.log." ;;
    esac
    say "Deployment: $status (waiting up to 15 minutes)"
    sleep 10
  done
  die "Deployment $DEPLOYMENT_ID is still pending. Check Greengrass in AWS and /greengrass/v2/logs/greengrass.log."
}

install_aws_cli() (
  # Unpacking and installing software must not inherit a private-file umask.
  umask 022
  unzip -q "$work/aws.zip" -d "$work"
  sudo "$work/aws/install"
)

configure_sso_defaults() {
  local session_name="${THING_NAME}-setup"
  # Create the selected profile before configuring its SSO session.
  aws configure set region ap-southeast-2 --profile "$AWS_PROFILE"
  aws configure set output json --profile "$AWS_PROFILE"
  aws configure set --sso-session "$session_name" sso_start_url https://spoke.awsapps.com/start
  aws configure set --sso-session "$session_name" sso_region ap-southeast-2
  aws configure set --sso-session "$session_name" sso_registration_scopes sso:account:access
  aws configure set sso_session "$session_name" --profile "$AWS_PROFILE"
}

main() {
  [[ "${1:-}" != --help ]] || { echo 'Usage: bash install.sh — interactive setup for a new 64-bit Raspberry Pi'; return; }
  # Keep prompts working when launched from a download command or SSH.
  exec </dev/tty
  [[ $EUID -ne 0 ]] || die 'Run as your normal Pi user; the wizard uses sudo when needed.'
  [[ $(uname -s) == Linux && $(uname -m) == aarch64 ]] || die 'Use Raspberry Pi OS Lite (64-bit).'
  command -v apt-get >/dev/null || die 'A Debian-based OS is required.'
  [[ -d /run/systemd/system ]] || die 'systemd must be running.'
  sudo -v
  [[ ! -e /greengrass/v2 ]] || die 'Greengrass already exists. This wizard is for new devices; no existing installation was changed.'

  umask 022
  work=$(mktemp -d)
  trap 'rm -rf -- "$work"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  # Non-secret answers survive a failed attempt. Never source this file.
  mkdir -p "$HOME/.config/spoke-onsite"
  ENV_FILE="$HOME/.config/spoke-onsite/setup.env"
  TOTAL_STAGES=5

  stage 'Device name and prerequisites'
  ask THING_NAME 'Unique device name (for example spoke-venue-pi-01):'
  valid_name "$THING_NAME" || die 'Device name must be 1–128 letters, digits, underscores or hyphens.'
  write_env THING_NAME "$THING_NAME"
  say 'This installs Java, Node.js 22 and AWS CLI, then provisions and deploys the onsite agent.'
  confirm 'Install prerequisites on this Pi?' || return 0
  sudo apt-get update
  sudo apt-get install -y ca-certificates default-jre-headless unzip curl jq
  if [[ ! -x /usr/bin/node ]] || ! /usr/bin/node -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 22 ? 0 : 1)'; then
    curl -fSL https://deb.nodesource.com/setup_22.x -o "$work/node-setup.sh"
    sudo bash "$work/node-setup.sh"
    sudo apt-get install -y nodejs
  fi
  sudo -u nobody /usr/bin/node -e 'if (Number(process.versions.node.split(".")[0]) < 22) process.exit(1)'
  export PATH="/usr/local/bin:$PATH"
  hash -r
  # Recover installs made by the original wizard under umask 077.
  if [[ -L /usr/local/bin/aws && ! -x /usr/local/bin/aws &&
        $(readlink /usr/local/bin/aws) == /usr/local/aws-cli/* ]]; then
    sudo chmod -R a+rX /usr/local/aws-cli
  fi
  if ! command -v aws >/dev/null; then
    curl -fSL https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o "$work/aws.zip"
    install_aws_cli
  fi
  local aws_version
  if ! aws_version=$(aws --version 2>&1); then
    printf '%s\n' "$aws_version" >&2
    die 'AWS CLI could not run as your user. Check /usr/local/bin/aws permissions and PATH.'
  fi
  [[ "$aws_version" == aws-cli/2.* ]] || die "AWS CLI v2 is required; found: $aws_version"

  stage 'AWS sign-in'
  export AWS_REGION=ap-southeast-2 AWS_DEFAULT_REGION=ap-southeast-2 AWS_PAGER='' AWS_CLI_AUTO_PROMPT=off
  export AWS_PROFILE=spoke-onsite-setup
  unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
  say 'Use an AWS role with IoT/Greengrass provisioning, IAM role setup and deployment permissions.'
  say 'SSO start URL: https://spoke.awsapps.com/start — SSO region: ap-southeast-2.'
  say 'Open the device-code URL on your laptop when prompted; choose the account that hosts the agent.'
  configure_sso_defaults
  if ! aws configure get sso_account_id --profile "$AWS_PROFILE" >/dev/null 2>&1 ||
     ! aws configure get sso_role_name --profile "$AWS_PROFILE" >/dev/null 2>&1; then
    say "Session ${THING_NAME}-setup is prefilled. Press Enter to keep it, then select your account and role."
    aws configure sso --profile "$AWS_PROFILE" --use-device-code --no-browser
  else
    aws sso login --profile "$AWS_PROFILE" --use-device-code --no-browser
  fi
  local account
  account=$(aws sts get-caller-identity --query Account --output text)
  [[ "$account" =~ ^[0-9]{12}$ ]] || die 'Could not determine the AWS account.'
  say "AWS account: $account; region: $AWS_REGION; device: $THING_NAME"
  confirm 'Use this AWS account and device name?' || return 0
  # Check for collisions without mistaking access/network errors for absence.
  if aws iot describe-thing --thing-name "$THING_NAME" >"$work/thing.json" 2>"$work/thing-error"; then
    die 'That device name already exists in AWS. Choose a new name; no device was changed.'
  elif ! grep -q ResourceNotFoundException "$work/thing-error"; then
    cat "$work/thing-error" >&2
    die 'Could not check whether the device name is available.'
  fi
  export THING_NAME THING_ARN="arn:aws:iot:$AWS_REGION:$account:thing/$THING_NAME"
  local latest
  latest=$(aws greengrassv2 list-components --scope PRIVATE --output json | jq -r \
    '[.components[] | select(.componentName == "com.spokehub.OnsiteAgent")][0].latestVersion.componentVersion // empty')
  [[ -n "$latest" ]] || die 'No onsite-agent release is published in this account/region. Publish it from spoke-hub first.'
  ask COMPONENT_VERSION "Agent version (Enter for latest published: $latest):"
  COMPONENT_VERSION=${COMPONENT_VERSION:-$latest}
  [[ "$COMPONENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die 'Expected a version such as 0.2.1.'
  export COMPONENT_VERSION
  aws greengrassv2 describe-component \
    --arn "arn:aws:greengrass:$AWS_REGION:$account:components:com.spokehub.OnsiteAgent:versions:$COMPONENT_VERSION" >/dev/null

  stage 'Hub credentials'
  configure_transport
  ask HUB_BASE_URL 'Hub API URL [https://www.spokehub.com.au/api]:'
  HUB_BASE_URL=${HUB_BASE_URL:-https://www.spokehub.com.au/api}
  HUB_BASE_URL=${HUB_BASE_URL%/}
  [[ "$HUB_BASE_URL" == https://* ]] || die 'Use an HTTPS Hub URL.'
  open_url "${HUB_BASE_URL%/api}"
  step 'In your organization settings, configure the member source and click Bootstrap Agent.'
  if [[ "$ONSITE_AGENT_TRANSPORT" == fbi ]]; then
    step 'Use the MAX Gaming member source with FBI live transport.'
  fi
  step 'Copy its client ID and single-line private key. Keep upstream credentials configured in Hub.'
  ask ONSITE_AGENT_CLIENT_ID 'Client ID:'
  ask_secret ONSITE_AGENT_PRIVATE_KEY 'Private key (hidden):'
  export HUB_BASE_URL ONSITE_AGENT_CLIENT_ID ONSITE_AGENT_PRIVATE_KEY
  validate_hub_credentials || die 'Invalid Hub credentials or URL.'
  write_env HUB_BASE_URL "$HUB_BASE_URL"
  write_env ONSITE_AGENT_CLIENT_ID "$ONSITE_AGENT_CLIENT_ID"
  (umask 077; deployment_json >"$work/deployment.json")
  unset ONSITE_AGENT_PRIVATE_KEY

  stage 'Provision and deploy'
  say "Create $THING_NAME in AWS account $account and deploy agent $COMPONENT_VERSION ($ONSITE_AGENT_TRANSPORT)."
  say 'The existing GreengrassV2TokenExchangeRole needs access to the agent artifact bucket (configured by spoke-hub).'
  confirm 'Provision this device and deploy the agent?' || return 0
  curl -fSL https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip -o "$work/greengrass.zip"
  unzip -q "$work/greengrass.zip" -d "$work/installer"
  # Only the installer subprocess receives temporary AWS credentials.
  (
    credentials=$(aws configure export-credentials --profile "$AWS_PROFILE" --format process)
    AWS_ACCESS_KEY_ID=$(jq -er .AccessKeyId <<<"$credentials")
    AWS_SECRET_ACCESS_KEY=$(jq -er .SecretAccessKey <<<"$credentials")
    AWS_SESSION_TOKEN=$(jq -er .SessionToken <<<"$credentials")
    export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    unset credentials AWS_PROFILE
    sudo --preserve-env=AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN \
      java -Droot=/greengrass/v2 -Dlog.store=FILE -jar "$work/installer/lib/Greengrass.jar" \
      --aws-region "$AWS_REGION" --thing-name "$THING_NAME" \
      --thing-policy-name GreengrassV2IoTThingPolicy \
      --tes-role-name GreengrassV2TokenExchangeRole \
      --tes-role-alias-name GreengrassCoreTokenExchangeRoleAlias \
      --component-default-user ggc_user:ggc_group --provision true --setup-system-service true
  )
  if [[ "$ONSITE_AGENT_TRANSPORT" == fbi ]]; then
    prepare_fbi_access
  fi
  sudo systemctl is-active --quiet greengrass
  DEPLOYMENT_ID=$(aws greengrassv2 create-deployment --cli-input-json "file://$work/deployment.json" --query deploymentId --output text)
  rm -f "$work/deployment.json"
  say "Created deployment $DEPLOYMENT_ID."

  stage 'Verify deployment'
  wait_for_deployment
  finish
  say "Agent $COMPONENT_VERSION deployed to $THING_NAME. Greengrass starts on boot."
  if [[ "$ONSITE_AGENT_TRANSPORT" == fbi ]]; then
    say 'Confirm a recent heartbeat in Hub, then verify a real MAX FBI.csv/FBI.sem export reaches Hub.'
  else
    say 'In Hub, confirm a recent agent heartbeat and request a sync to verify venue connectivity.'
  fi
  say 'Logs: sudo tail -n 100 -f /greengrass/v2/logs/com.spokehub.OnsiteAgent.log'
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
